### ISSUE TITLE
Audiobook title + author name?

### ISSUE THREAD

**Issue by Thomas-O** [robwebset/script.audiobooks#1]
Hi,

Might it be possible for each audiobook title to include the author's (artist's) name? Though just in the list of audiobooks.

Also, when there's only one file in the folder could the audiobook title be replaced with Play? So that the most you'll see inside the selected audiobook is Play, Resume from .... and the audiobook cover. 

Lastly, might it be possible to provide the option to disable the Resume chapter number in parenthesis? There's not much point when there's just one file / chapter.

I hope this isn't too much to ask. The add-on is already providing great service to my friends and family. It's just that almost all our audiobooks are audible audiobooks stripped of the DRM and then concatenated in to single large files. For easy sharing and portage. The tweak would remove the quirk of having both the audiobook folder and contents having exactly the same title. Making the experience just that bit smoother and that bit nicer.

While I'm here, I want to thank you (and Orac) for all the time and effort you've put in to developing this add-on. My family and friends really appreciate the support for audiobooks, audio drama etc. It's such a pity that fences can't be mended and the support for audiobooks woven in to the core of Kodi's code.

Thanks for your time.

Thomas

**Comment by robwebset** [comment]
Hi @Thomas-O 

I think I've managed to implement everything you have requested. From the changelog:

> v100.7.0 (2016-12-02)
> - Only show Chapter number on resume if more than one chapter
> - Option to display Artist name on book list
> - Option to show play button rather than chapter name (when only one chapter)

You will need to enable things in the settings:

https://github.com/robwebset/script.audiobooks/wiki#General

To get the change in display data, and to see it on existing audiobooks you'll need to do a "Clear AudioBook Details Cache" from the settings.

Please let me know how you get on.

Thanks
Rob

In Repo As: AudioBooks v100.7.0

**Comment by Thomas-O** [comment]
Crikey, that was quick. To be honest, I really wasn't expecting you to drop everything and rush to my aid. So it was a lovely surprise when I revisited the topic this morning. I'll give it a whirl and see how it goes. Thank you so much from all of us.

Thomas

**Comment by Thomas-O** [comment]
Eureka. It works, and it is very, very cool. Thanks once again for a fantastic add-on.

Thomas
