### ISSUE TITLE
Sorry for being a pest...

### ISSUE THREAD

**Issue by Thomas-O** [robwebset/script.audiobooks#3]
Sorry to bother you again.

I tried and failed to change the audiobook add-on's background / fanart by replacing the fanart.jpg in the script.audiobooks folder. If it's possible to change the background could you briefly tell me how? Or perhaps add an option to the Configuration.

Also, might it be possible to add a 'Delete Audiobook' option to the context menu?

BTW, the problem with the uRepo repository was more to do with the website. The link to which was temporarily taking me to Reading University's website. I assumed uRepo had shut up shop or something.

**Comment by robwebset** [comment]
Please post all requests to the URepo forum:

http://www.urepo.org/forum/viewtopic.php?f=5&t=1768
