### ISSUE TITLE
taking over this addon

### ISSUE THREAD

**Issue by twisted-fire-starter** [robwebset/script.audiobooks#5]
hi was wondering if it would be ok to take over this addon please

**Comment by robwebset** [comment]
Yes, that would be good - nice to keep these things alive.

If you are OK I will transfer both:
   script.audiobooks
   kodi.ffmpeg.bundles

To you (as they are connected).

**Comment by robwebset** [comment]
@twisted-fire-starter please can you let me know if you are still interested in taking over the audiobooks addons?
